In [13]:
import numpy as np

D = 5
N = 7

In [15]:
# Sum node
x = np.random.rand(1,D)
y = np.repeat(x, N, axis=0)

dy = np.random.rand(N, D)
dx = np.sum(dy, axis=0, keepdims=True)

print('dy:', dy,'\n')
print('dx:', dx)
print()
print("dy.shape : {}\ndx.shape : {}".format(dy.shape, dx.shape))

dy: [[0.75740027 0.7909099  0.60089373 0.22906755 0.45901743]
 [0.39335043 0.76584841 0.95832532 0.20522147 0.61902571]
 [0.12095017 0.86931678 0.09828762 0.34759943 0.94446377]
 [0.21495876 0.56945983 0.05279708 0.49606262 0.54809216]
 [0.26740045 0.80058391 0.10208348 0.9578795  0.87701552]
 [0.02605032 0.36238676 0.7940286  0.94010599 0.62375371]
 [0.30641833 0.40245546 0.94786811 0.88561025 0.70315681]] 

dx: [[2.08652873 4.56096106 3.55428394 4.0615468  4.77452511]]

dy.shape : (7, 5)
dx.shape : (1, 5)


In [17]:
# repeat node
x = np.random.rand(N, D)
y = np.sum(x, axis=0, keepdims=True)

dy = np.random.rand(1, D)
dx = np.repeat(dx, N, axis=0)

print('dy:', dy,'\n')
print('dx:', dx)
print()
print("dy.shape : {}\ndx.shape : {}".format(dy.shape, dx.shape))

dy: [[0.24666331 0.99869589 0.44056486 0.28887607 0.86778724]] 

dx: [[0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]
 [0.93228892 0.59910329 0.10171611 0.3481869  0.42151672]]

dy.shape : (1, 5)
dx.shape : (7, 5)


In [2]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None

    def forward(self, x, y):
        self.x = x          # save the input values for the backward propagation process
        self.y = y
        out = x * y

        return out

    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x

        return dx, dy
    

apple_price = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

o1 = mul_apple_layer.forward(apple_price, apple_num)
o2 = mul_tax_layer.forward(o1, tax)

print(o2)

dprice = 1
dapple_set, dtax = mul_tax_layer.backward(dprice)
dapple_price, dapple_num = mul_apple_layer.backward(dapple_set)

print(dapple_price, dtax)

220.00000000000003
2.2 200
